# ForgeLegalizerVerifier configuration for Velocity plugin.
# Authors: threefusii (BromineMC), VidTu (BromineMC).

# Player kick message for hack-alike-Forge.
# Leave empty to disable.
# Placeholders:
# - "%name%" - Player name
# - "%uuid%" - Player UUID
# - "%server%" - Backend server name
# Using MiniMessage (https://docs.advntr.dev/minimessage/) formatting.
kickMessage:
  - '<red>> Unsupported Minecraft Forge Version</red>'
  - ''
  - 'Forge versions <yellow>1.18.2 -> 1.19.4</yellow> contain a bug that provides an <gold>unfair advantage</gold>.'
  - 'To prevent false cheat accusations, you <red><u>won''t be able to join</u></red>.'
  - 'More info: <aqua>https://tinyurl.com/forge-reach-bug</aqua>'
  - ''
  - 'Please use another mod loader (e.g. Fabric or Quilt),'
  - 'another Minecraft version, or the vanilla (unmodified)'
  - 'client. If you still want to use Forge, download and install'
  - 'the <yellow>ForgeLegalizer</yellow> mod from:'
  - 'Modrinth: <green>https://modrinth.com/mod/forgelegalizer</green>'
  - 'GitHub: <aqua>https://github.com/BromineMC/ForgeLegalizer/releases</aqua>'
  - ''
  - '<gray>%name% (%uuid%) from %server%</gray>'

# Admin notify message for hack-alike-Forge.
# Leave empty to disable.
# Placeholders:
# - "%name%" - Player name
# - "%uuid%" - Player UUID
# - "%server%" - Backend server name
# Using MiniMessage (https://docs.advntr.dev/minimessage/) formatting.
notifyMessage:
  - '<yellow>%name%</yellow> (<gray>%uuid%</gray>) joined using <red>hack-alike-Forge</red>. (<green>%server%</green>)'

# Commands to execute on hack-alike-Forge players.
# Placeholders:
# - "%name%" - Player name
# - "%uuid%" - Player UUID
# - "%server%" - Backend server name
commands:
  - 'example_say %name% is bad.'
  - 'example_ban_command %uuid% 30m hacks'

# Regular expression (regex) of the Forge-alike brands.
# Clients with these brands OR with any of the channels below will be checked for ForgeLegalizer.
forgeBrand: '^(forge|fml,forge|fml,forge,LiteLoader|neoforge)$'

# Regular expression (regex) of the Forge-alike channels.
# Clients with any of these channels OR with brands above will be checked for ForgeLegalizer.
forgeChannel: '^(fml:loginwrapper|forge:tier_sorting|fml:handshake|fml:play|forge:split)$'