name: Build
on: [ pull_request, push, workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Validate wrapper'
        uses: gradle/wrapper-validation-action@v1
      - name: 'Setup JDK'
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'microsoft'
          cache: gradle
      - name: 'Make wrapper executable'
        run: chmod +x ./gradlew
      - name: 'Build'
        run: ./gradlew build
      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            forge-1.18.2/build/libs/
            forge-1.19.4/build/libs/
            verifier-spigot/build/libs/
            verifier-velocity/build/libs/
            verifier-bungee/build/libs/
